# Generated by Django 3.0.1 on 2020-11-07 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('type_of_cource', models.CharField(choices=[('Груповые', 'Груповые'), ('Индивидуальные', 'Индивидуальные')], max_length=100, verbose_name='Тип проведения')),
                ('attendance', models.CharField(choices=[('Очные', 'Очные'), ('Заочные', 'Заочные')], max_length=100, verbose_name='Вид проведения')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала курсов')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания курсов')),
                ('study_hours', models.IntegerField(verbose_name='Колличество часов обучения')),
                ('base_education', models.CharField(choices=[('Среднее', 'Среднее'), ('Высшее', 'Высшее')], max_length=100, verbose_name='Базовое образование')),
                ('graduate_control', models.CharField(choices=[('Квалификационная работа', 'Квалификационная работа'), ('Экзамен', 'Экзамен'), ('Собеседование', 'Собеседование')], max_length=100, verbose_name='Вид выпускного контроля')),
                ('graduate_document', models.CharField(choices=[('Документ государственного образца', 'Документ государственного образца'), ('Сертификат', 'Сертификат')], max_length=100, verbose_name='Вид выдаваемого документа')),
                ('price', models.IntegerField(verbose_name='Стоимость обучения')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название организации')),
                ('email', models.CharField(max_length=100, verbose_name='Электронный адрес')),
                ('web_site', models.CharField(max_length=100, verbose_name='Адрес сайта')),
                ('document_number', models.IntegerField(verbose_name='Номер документа')),
                ('document_series', models.CharField(max_length=100, verbose_name='Вид документа')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('hours', models.IntegerField(verbose_name='Колличество часов')),
                ('cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cource.Cource')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=100, verbose_name='День')),
                ('from_time', models.TimeField(verbose_name='Начало занятия')),
                ('to_time', models.TimeField(verbose_name='Конец занятия')),
                ('cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cource.Cource')),
            ],
        ),
        migrations.AddField(
            model_name='cource',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cource.Organization'),
        ),
    ]
