# Generated by Django 3.0.1 on 2020-11-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cource',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания курсов'),
        ),
        migrations.AlterField(
            model_name='cource',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала курсов'),
        ),
    ]
